language: python
sudo: false

cache:
  directories:
    - $HOME/cache

python:
#  - "2.6"
  - "2.7"
#  - "3.2"
#  - "3.3"
#  - "3.4"
#  - "3.5"

compiler:
#  - gcc
  - clang

env:
  - TOXCORE_REPO=TokTok/c-toxcore

addons: {apt: {packages: [yasm]}}

before_script:
  - export CACHE_DIR="$HOME/cache"
  - export CFLAGS="-I$CACHE_DIR/usr/include"
  - export LDFLAGS="-L$CACHE_DIR/usr/lib"
  - export LD_LIBRARY_PATH="$CACHE_DIR/usr/lib"
  - export PKG_CONFIG_PATH="$CACHE_DIR/usr/lib/pkgconfig"
  - tools/install-deps.sh > /dev/null

script:
  - pip install .
  - python tests/tests.py
