language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
compiler:
  - gcc
  - clang
before_script:
  # installing libsodium, needed for Core
  - git clone git://github.com/jedisct1/libsodium.git
  - cd libsodium
  - git checkout tags/0.4.2
  - ./autogen.sh
  - ./configure --prefix=/usr
  - make -j2 > /dev/null
  - sudo make install > /dev/null
  - cd ..
  # installing libopus, needed for audio encoding/decoding
  - wget http://downloads.xiph.org/releases/opus/opus-1.0.3.tar.gz > /dev/null
  - tar xzf opus-1.0.3.tar.gz > /dev/null
  - cd opus-1.0.3
  - ./configure
  - make -j3 > /dev/null
  - sudo make install > /dev/null
  - cd ..
  # installing vpx
  - sudo apt-get install yasm
  - git clone http://git.chromium.org/webm/libvpx.git > /dev/null
  - cd libvpx
  - ./configure
  - make -j3 >/dev/null
  - sudo make install > /dev/null
  - cd ..
  # creating librarys' links and updating cache
  - sudo ldconfig
  - git clone https://github.com/irungentoo/ProjectTox-Core.git toxcore
  - cd toxcore
  - autoreconf -i
  - ./configure --prefix=/usr --disable-tests --disable-ntox --disable-dht-bootstrap-daemon
  - make -j2
  - sudo make install
  - cd ..
script:
  - pip install .
  - python tests/tests.py
